import {createAction} from "redux-actions";

const API_PENDING = createAction('API_PENDING');

const FETCH_ALL_CONTACTS = createAction("FETCH_ALL_CONTACTS");
const FETCH_CONTACT = createAction('FETCH_CONTACT');
const CREATE_CONTACT = createAction('CREATE_CONTACT');
const UPDATE_CONTACT = createAction('UPDATE_CONTACT');
const DELETE_CONTACT = createAction('DELETE_CONTACT');

const FETCH_ALL_CONTACTS_SUCCESS = createAction('FETCH_ALL_CONTACTS_SUCCESS');

const FETCH_ALL_CONTACTS_FAILURE = createAction('FETCH_ALL_CONTACTS_FAILURE');

const FETCH_CONTACT_SUCCESS = createAction('FETCH_CONTACT_SUCCESS');
const CREATE_CONTACT_SUCCESS = createAction('CREATE_CONTACT_SUCCESS');
const UPDATE_CONTACT_SUCCESS = createAction('UPDATE_CONTACT_SUCCESS');
const DELETE_CONTACT_SUCCESS = createAction('DELETE_CONTACT_SUCCESS');

const API_FAILURE = createAction('API_FAILURE');

const EDIT_CONTACT = createAction('EDIT_CONTACT');
const CANCEL_EDIT = createAction('CANCEL_EDIT');

export {API_PENDING,
  FETCH_ALL_CONTACTS, FETCH_CONTACT, CREATE_CONTACT, UPDATE_CONTACT, DELETE_CONTACT,
  FETCH_ALL_CONTACTS_SUCCESS, FETCH_ALL_CONTACTS_FAILURE,
  FETCH_CONTACT_SUCCESS, CREATE_CONTACT_SUCCESS, UPDATE_CONTACT_SUCCESS, DELETE_CONTACT_SUCCESS,
  API_FAILURE,
  EDIT_CONTACT, CANCEL_EDIT};